# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.19.3"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cert
    sigh
    build_app(
	    scheme: "whatson",
	    export_method: "app-store"
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    version = ENV["BUILD_NUMBER"]
    update_build(version)
    gym(scheme: "whatson")
    upload_to_testflight(skip_waiting_for_build_processing: false)
    upload_to_appstore(force: true, build_number: version)
  end

end

def update_build(version)
   splits = version.split(".") # ["0", "1", "4"]
   buildnumber = "#{splits.first}#{splits[1].rjust(2, '0')}#{splits[2].rjust(2, '0')}"
   increment_build_number(
      build_number: buildnumber
   )
   increment_version_number(
      version_number: version
   )
end
