# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.19.3"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    cert
    sigh
    version = prompt(text: "version number: ")
    update_build(version)
    clean_build_artifacts
    commit_version_bump(
      xcodeproj: "whatson.xcodeproj"
    )
    gym(scheme: "whatson")
    pilot(skip_waiting_for_build_processing: true)
    add_git_tag(
        tag: "#{version}"
    )
    push_git_tags
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "whatson")
    deliver(force: true)
    # frameit
  end

end

def update_build(version)
   splits = version.split(".") # ["0", "1", "4"]
   buildnumber = "#{splits.first}#{splits[1].rjust(2, '0')}#{splits[2].rjust(2, '0')}"
   increment_build_number(
      build_number: buildnumber
   )
   increment_version_number(
      version_number: version
   )
end
