package com.example.compose
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006e2a)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF65ff8d)
val md_theme_light_onPrimaryContainer = Color(0xFF002107)
val md_theme_light_secondary = Color(0xFF2b5ea7)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd6e3ff)
val md_theme_light_onSecondaryContainer = Color(0xFF001b3f)
val md_theme_light_tertiary = Color(0xFF39656c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbceaf3)
val md_theme_light_onTertiaryContainer = Color(0xFF001f24)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcf7)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfcf7)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdde5d9)
val md_theme_light_onSurfaceVariant = Color(0xFF414940)
val md_theme_light_outline = Color(0xFF727970)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1eb)
val md_theme_light_inverseSurface = Color(0xFF2e312d)

val md_theme_dark_primary = Color(0xFF29e369)
val md_theme_dark_onPrimary = Color(0xFF003911)
val md_theme_dark_primaryContainer = Color(0xFF00531d)
val md_theme_dark_onPrimaryContainer = Color(0xFF65ff8d)
val md_theme_dark_secondary = Color(0xFFa8c7ff)
val md_theme_dark_onSecondary = Color(0xFF002f67)
val md_theme_dark_secondaryContainer = Color(0xFF00458d)
val md_theme_dark_onSecondaryContainer = Color(0xFFd6e3ff)
val md_theme_dark_tertiary = Color(0xFFa1ced6)
val md_theme_dark_onTertiary = Color(0xFF00363d)
val md_theme_dark_tertiaryContainer = Color(0xFF1f4d54)
val md_theme_dark_onTertiaryContainer = Color(0xFFbceaf3)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe1e3dd)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe1e3dd)
val md_theme_dark_surfaceVariant = Color(0xFF414940)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c9be)
val md_theme_dark_outline = Color(0xFF8b9389)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe1e3dd)

val seed = Color(0xFF00d65e)
val error = Color(0xFFba1b1b)