//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarSource.java
//

#ifndef _UkCoAmlcurranSocialCalendarSource_H_
#define _UkCoAmlcurranSocialCalendarSource_H_

#include "J2ObjC_header.h"

@class UkCoAmlcurranSocialCoreSparseArray;
@protocol UkCoAmlcurranSocialCalendarItem;
@protocol UkCoAmlcurranSocialTime;

@interface UkCoAmlcurranSocialCalendarSource : NSObject

#pragma mark Public

- (instancetype)initWithUkCoAmlcurranSocialCoreSparseArray:(UkCoAmlcurranSocialCoreSparseArray *)calendarItems
                                                   withInt:(jint)daysSize
                               withUkCoAmlcurranSocialTime:(id<UkCoAmlcurranSocialTime>)now;

- (jint)count;

- (jboolean)isEmptyAtWithInt:(jint)position;

- (id<UkCoAmlcurranSocialCalendarItem>)itemAtWithInt:(jint)position;

@end

J2OBJC_EMPTY_STATIC_INIT(UkCoAmlcurranSocialCalendarSource)

FOUNDATION_EXPORT void UkCoAmlcurranSocialCalendarSource_initWithUkCoAmlcurranSocialCoreSparseArray_withInt_withUkCoAmlcurranSocialTime_(UkCoAmlcurranSocialCalendarSource *self, UkCoAmlcurranSocialCoreSparseArray *calendarItems, jint daysSize, id<UkCoAmlcurranSocialTime> now);

FOUNDATION_EXPORT UkCoAmlcurranSocialCalendarSource *new_UkCoAmlcurranSocialCalendarSource_initWithUkCoAmlcurranSocialCoreSparseArray_withInt_withUkCoAmlcurranSocialTime_(UkCoAmlcurranSocialCoreSparseArray *calendarItems, jint daysSize, id<UkCoAmlcurranSocialTime> now) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialCalendarSource)

#endif // _UkCoAmlcurranSocialCalendarSource_H_
