//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarSlot.java
//

#include "J2ObjC_header.h"

#pragma push_macro("CalendarSlot_INCLUDE_ALL")
#ifdef CalendarSlot_RESTRICT
#define CalendarSlot_INCLUDE_ALL 0
#else
#define CalendarSlot_INCLUDE_ALL 1
#endif
#undef CalendarSlot_RESTRICT

#if !defined (SCCalendarSlot_) && (CalendarSlot_INCLUDE_ALL || defined(SCCalendarSlot_INCLUDE))
#define SCCalendarSlot_

@protocol JavaUtilList;
@protocol SCCalendarItem;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface SCCalendarSlot : NSObject

#pragma mark Public

- (instancetype)init;

- (void)addItemWithSCCalendarItem:(id<SCCalendarItem>)item;

- (jint)count;

- (id<SCCalendarItem> __nullable)firstItem;

- (jboolean)isEmpty;

- (id<JavaUtilList> __nonnull)items;

@end

J2OBJC_EMPTY_STATIC_INIT(SCCalendarSlot)

FOUNDATION_EXPORT void SCCalendarSlot_init(SCCalendarSlot *self);

FOUNDATION_EXPORT SCCalendarSlot *new_SCCalendarSlot_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SCCalendarSlot *create_SCCalendarSlot_init();

J2OBJC_TYPE_LITERAL_HEADER(SCCalendarSlot)

@compatibility_alias UkCoAmlcurranSocialCalendarSlot SCCalendarSlot;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif

#pragma pop_macro("CalendarSlot_INCLUDE_ALL")
