//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarItem.java
//

#ifndef _SCCalendarItem_H_
#define _SCCalendarItem_H_

#include "J2ObjC_header.h"

@protocol SCTime;

@protocol SCCalendarItem < NSObject, JavaObject >

- (NSString *)title;

- (jint)startDay;

- (id<SCTime>)startTime;

- (jboolean)isEmpty;

@end

J2OBJC_EMPTY_STATIC_INIT(SCCalendarItem)

J2OBJC_TYPE_LITERAL_HEADER(SCCalendarItem)

#define UkCoAmlcurranSocialCalendarItem SCCalendarItem

#endif // _SCCalendarItem_H_
