//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarSlot.java
//

#include "CalendarItem.h"
#include "CalendarSlot.h"
#include "J2ObjC_source.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@interface SCCalendarSlot () {
 @public
  id<JavaUtilList> calendarItems_;
}

@end

J2OBJC_FIELD_SETTER(SCCalendarSlot, calendarItems_, id<JavaUtilList>)

@implementation SCCalendarSlot

- (id<SCCalendarItem>)firstItem {
  return [((id<JavaUtilList>) nil_chk(calendarItems_)) getWithInt:0];
}

- (void)addItemWithSCCalendarItem:(id<SCCalendarItem>)item {
  [((id<JavaUtilList>) nil_chk(self->calendarItems_)) addWithId:item];
}

- (jint)count {
  return [((id<JavaUtilList>) nil_chk(calendarItems_)) size];
}

- (jboolean)isEmpty {
  return [((id<JavaUtilList>) nil_chk(calendarItems_)) isEmpty];
}

J2OBJC_IGNORE_DESIGNATED_BEGIN
- (instancetype)init {
  SCCalendarSlot_init(self);
  return self;
}
J2OBJC_IGNORE_DESIGNATED_END

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "firstItem", NULL, "Luk.co.amlcurran.social.CalendarItem;", 0x1, NULL, NULL },
    { "addItemWithSCCalendarItem:", "addItem", "V", 0x1, NULL, NULL },
    { "count", NULL, "I", 0x1, NULL, NULL },
    { "isEmpty", NULL, "Z", 0x1, NULL, NULL },
    { "init", NULL, NULL, 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "calendarItems_", NULL, 0x12, "Ljava.util.List;", NULL, "Ljava/util/List<Luk/co/amlcurran/social/CalendarItem;>;", .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _SCCalendarSlot = { 2, "CalendarSlot", "uk.co.amlcurran.social", NULL, 0x1, 5, methods, 1, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCCalendarSlot;
}

@end

void SCCalendarSlot_init(SCCalendarSlot *self) {
  (void) NSObject_init(self);
  self->calendarItems_ = new_JavaUtilArrayList_init();
}

SCCalendarSlot *new_SCCalendarSlot_init() {
  SCCalendarSlot *self = [SCCalendarSlot alloc];
  SCCalendarSlot_init(self);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SCCalendarSlot)
