//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarItem.java
//

#include "CalendarItem.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Timestamp.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface SCCalendarItem : NSObject

@end

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

@implementation SCCalendarItem

+ (IOSObjectArray *)__annotations_title {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_startTime {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_endTime {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "title", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "startTime", NULL, "Luk.co.amlcurran.social.Timestamp;", 0x401, NULL, NULL },
    { "endTime", NULL, "Luk.co.amlcurran.social.Timestamp;", 0x401, NULL, NULL },
    { "isEmpty", NULL, "Z", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _SCCalendarItem = { 2, "CalendarItem", "uk.co.amlcurran.social", NULL, 0x609, 4, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCCalendarItem;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCCalendarItem)
