//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarItem.java
//

#ifndef _UkCoAmlcurranSocialCalendarItem_H_
#define _UkCoAmlcurranSocialCalendarItem_H_

#include "J2ObjC_header.h"

@protocol UkCoAmlcurranSocialCalendarItem < NSObject, JavaObject >

- (NSString *)title;

- (jint)startDay;

- (jlong)startTime;

- (jboolean)isEmpty;

@end

J2OBJC_EMPTY_STATIC_INIT(UkCoAmlcurranSocialCalendarItem)

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialCalendarItem)

#endif // _UkCoAmlcurranSocialCalendarItem_H_
