//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarSlot.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CalendarSlot")
#ifdef RESTRICT_CalendarSlot
#define INCLUDE_ALL_CalendarSlot 0
#else
#define INCLUDE_ALL_CalendarSlot 1
#endif
#undef RESTRICT_CalendarSlot

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SCCalendarSlot_) && (INCLUDE_ALL_CalendarSlot || defined(INCLUDE_SCCalendarSlot))
#define SCCalendarSlot_

@protocol JavaUtilList;
@protocol SCCalendarItem;

@interface SCCalendarSlot : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (void)addItemWithSCCalendarItem:(id<SCCalendarItem>)item;

- (jint)count;

- (id<SCCalendarItem> __nullable)firstItem;

- (jboolean)isEmpty;

- (id<JavaUtilList> __nonnull)items;

@end

J2OBJC_EMPTY_STATIC_INIT(SCCalendarSlot)

FOUNDATION_EXPORT void SCCalendarSlot_init(SCCalendarSlot *self);

FOUNDATION_EXPORT SCCalendarSlot *new_SCCalendarSlot_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SCCalendarSlot *create_SCCalendarSlot_init(void);

J2OBJC_TYPE_LITERAL_HEADER(SCCalendarSlot)

@compatibility_alias UkCoAmlcurranSocialCalendarSlot SCCalendarSlot;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_CalendarSlot")
