//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarSlot.java
//

#ifndef _CalendarSlot_H_
#define _CalendarSlot_H_

#include "J2ObjC_header.h"

@protocol SCCalendarItem;

@interface SCCalendarSlot : NSObject

#pragma mark Public

- (instancetype)init;

- (void)addItemWithSCCalendarItem:(id<SCCalendarItem>)item;

- (jint)count;

- (id<SCCalendarItem>)firstItem;

- (jboolean)isEmpty;

@end

J2OBJC_EMPTY_STATIC_INIT(SCCalendarSlot)

FOUNDATION_EXPORT void SCCalendarSlot_init(SCCalendarSlot *self);

FOUNDATION_EXPORT SCCalendarSlot *new_SCCalendarSlot_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(SCCalendarSlot)

@compatibility_alias UkCoAmlcurranSocialCalendarSlot SCCalendarSlot;

#endif // _CalendarSlot_H_
