//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarSource.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_CalendarSource")
#ifdef RESTRICT_CalendarSource
#define INCLUDE_ALL_CalendarSource 0
#else
#define INCLUDE_ALL_CalendarSource 1
#endif
#undef RESTRICT_CalendarSource

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SCCalendarSource_) && (INCLUDE_ALL_CalendarSource || defined(INCLUDE_SCCalendarSource))
#define SCCalendarSource_

@class SCCalendarSlot;
@class UkCoAmlcurranSocialUtilsSparseArray;
@protocol SCCalendarItem;
@protocol SCTimeCalculator;
@protocol SCTimeRepository;

@interface SCCalendarSource : NSObject

#pragma mark Public

- (instancetype __nonnull)initWithUkCoAmlcurranSocialUtilsSparseArray:(UkCoAmlcurranSocialUtilsSparseArray *)calendarItems
                                                              withInt:(jint)daysSize
                                                 withSCTimeCalculator:(id<SCTimeCalculator>)timeCalculator
                                                 withSCTimeRepository:(id<SCTimeRepository>)timeRepository;

- (jint)count;

- (jboolean)isEmptySlotWithInt:(jint)position;

- (id<SCCalendarItem> __nullable)itemAtWithInt:(jint)position;

- (SCCalendarSlot * __nonnull)slotAtWithInt:(jint)position;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(SCCalendarSource)

FOUNDATION_EXPORT void SCCalendarSource_initWithUkCoAmlcurranSocialUtilsSparseArray_withInt_withSCTimeCalculator_withSCTimeRepository_(SCCalendarSource *self, UkCoAmlcurranSocialUtilsSparseArray *calendarItems, jint daysSize, id<SCTimeCalculator> timeCalculator, id<SCTimeRepository> timeRepository);

FOUNDATION_EXPORT SCCalendarSource *new_SCCalendarSource_initWithUkCoAmlcurranSocialUtilsSparseArray_withInt_withSCTimeCalculator_withSCTimeRepository_(UkCoAmlcurranSocialUtilsSparseArray *calendarItems, jint daysSize, id<SCTimeCalculator> timeCalculator, id<SCTimeRepository> timeRepository) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SCCalendarSource *create_SCCalendarSource_initWithUkCoAmlcurranSocialUtilsSparseArray_withInt_withSCTimeCalculator_withSCTimeRepository_(UkCoAmlcurranSocialUtilsSparseArray *calendarItems, jint daysSize, id<SCTimeCalculator> timeCalculator, id<SCTimeRepository> timeRepository);

J2OBJC_TYPE_LITERAL_HEADER(SCCalendarSource)

@compatibility_alias UkCoAmlcurranSocialCalendarSource SCCalendarSource;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_CalendarSource")
