//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarItem.java
//

#include "CalendarItem.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

@interface SCCalendarItem : NSObject

@end

__attribute__((unused)) static IOSObjectArray *SCCalendarItem__Annotations$0();

__attribute__((unused)) static IOSObjectArray *SCCalendarItem__Annotations$1();

__attribute__((unused)) static IOSObjectArray *SCCalendarItem__Annotations$2();

@implementation SCCalendarItem

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LNSString;", 0x401, -1, -1, -1, -1, 0, -1 },
    { NULL, "LSCTimestamp;", 0x401, -1, -1, -1, -1, 1, -1 },
    { NULL, "LSCTimestamp;", 0x401, -1, -1, -1, -1, 2, -1 },
    { NULL, "Z", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(title);
  methods[1].selector = @selector(startTime);
  methods[2].selector = @selector(endTime);
  methods[3].selector = @selector(isEmpty);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&SCCalendarItem__Annotations$0, (void *)&SCCalendarItem__Annotations$1, (void *)&SCCalendarItem__Annotations$2 };
  static const J2ObjcClassInfo _SCCalendarItem = { "CalendarItem", "uk.co.amlcurran.social", ptrTable, methods, NULL, 7, 0x609, 4, 0, -1, -1, -1, -1, -1 };
  return &_SCCalendarItem;
}

@end

IOSObjectArray *SCCalendarItem__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SCCalendarItem__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SCCalendarItem__Annotations$2() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCCalendarItem)
