//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/core/ContainerHelpers.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ContainerHelpers")
#ifdef RESTRICT_ContainerHelpers
#define INCLUDE_ALL_ContainerHelpers 0
#else
#define INCLUDE_ALL_ContainerHelpers 1
#endif
#undef RESTRICT_ContainerHelpers

#if !defined (UkCoAmlcurranSocialCoreContainerHelpers_) && (INCLUDE_ALL_ContainerHelpers || defined(INCLUDE_UkCoAmlcurranSocialCoreContainerHelpers))
#define UkCoAmlcurranSocialCoreContainerHelpers_

@class IOSIntArray;
@class IOSLongArray;
@class IOSObjectArray;

@interface UkCoAmlcurranSocialCoreContainerHelpers : NSObject

#pragma mark Public

- (instancetype)init;

+ (jboolean)equalWithId:(id)a
                 withId:(id)b;

+ (jint)idealByteArraySizeWithInt:(jint)need;

+ (jint)idealIntArraySizeWithInt:(jint)need;

+ (jint)idealLongArraySizeWithInt:(jint)need;

#pragma mark Package-Private

+ (jint)binarySearchWithIntArray:(IOSIntArray *)array
                         withInt:(jint)size
                         withInt:(jint)value;

+ (jint)binarySearchWithLongArray:(IOSLongArray *)array
                          withInt:(jint)size
                         withLong:(jlong)value;

@end

J2OBJC_STATIC_INIT(UkCoAmlcurranSocialCoreContainerHelpers)

inline IOSIntArray *UkCoAmlcurranSocialCoreContainerHelpers_get_EMPTY_INTS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSIntArray *UkCoAmlcurranSocialCoreContainerHelpers_EMPTY_INTS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(UkCoAmlcurranSocialCoreContainerHelpers, EMPTY_INTS, IOSIntArray *)

inline IOSLongArray *UkCoAmlcurranSocialCoreContainerHelpers_get_EMPTY_LONGS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSLongArray *UkCoAmlcurranSocialCoreContainerHelpers_EMPTY_LONGS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(UkCoAmlcurranSocialCoreContainerHelpers, EMPTY_LONGS, IOSLongArray *)

inline IOSObjectArray *UkCoAmlcurranSocialCoreContainerHelpers_get_EMPTY_OBJECTS();
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT IOSObjectArray *UkCoAmlcurranSocialCoreContainerHelpers_EMPTY_OBJECTS;
J2OBJC_STATIC_FIELD_OBJ_FINAL(UkCoAmlcurranSocialCoreContainerHelpers, EMPTY_OBJECTS, IOSObjectArray *)

FOUNDATION_EXPORT void UkCoAmlcurranSocialCoreContainerHelpers_init(UkCoAmlcurranSocialCoreContainerHelpers *self);

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreContainerHelpers *new_UkCoAmlcurranSocialCoreContainerHelpers_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreContainerHelpers *create_UkCoAmlcurranSocialCoreContainerHelpers_init();

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_idealIntArraySizeWithInt_(jint need);

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_idealLongArraySizeWithInt_(jint need);

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_idealByteArraySizeWithInt_(jint need);

FOUNDATION_EXPORT jboolean UkCoAmlcurranSocialCoreContainerHelpers_equalWithId_withId_(id a, id b);

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_binarySearchWithIntArray_withInt_withInt_(IOSIntArray *array, jint size, jint value);

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_binarySearchWithLongArray_withInt_withLong_(IOSLongArray *array, jint size, jlong value);

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialCoreContainerHelpers)

#endif

#pragma pop_macro("INCLUDE_ALL_ContainerHelpers")
