//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/core/ContainerHelpers.java
//

#ifndef _ContainerHelpers_H_
#define _ContainerHelpers_H_

#include "J2ObjC_header.h"

@class IOSIntArray;
@class IOSLongArray;
@class IOSObjectArray;

@interface UkCoAmlcurranSocialCoreContainerHelpers : NSObject

#pragma mark Public

- (instancetype)init;

+ (jboolean)equalWithId:(id)a
                 withId:(id)b;

+ (jint)idealByteArraySizeWithInt:(jint)need;

+ (jint)idealIntArraySizeWithInt:(jint)need;

+ (jint)idealLongArraySizeWithInt:(jint)need;

#pragma mark Package-Private

+ (jint)binarySearchWithIntArray:(IOSIntArray *)array
                         withInt:(jint)size
                         withInt:(jint)value;

+ (jint)binarySearchWithLongArray:(IOSLongArray *)array
                          withInt:(jint)size
                         withLong:(jlong)value;

@end

J2OBJC_STATIC_INIT(UkCoAmlcurranSocialCoreContainerHelpers)

FOUNDATION_EXPORT IOSIntArray *UkCoAmlcurranSocialCoreContainerHelpers_EMPTY_INTS_;
J2OBJC_STATIC_FIELD_GETTER(UkCoAmlcurranSocialCoreContainerHelpers, EMPTY_INTS_, IOSIntArray *)

FOUNDATION_EXPORT IOSLongArray *UkCoAmlcurranSocialCoreContainerHelpers_EMPTY_LONGS_;
J2OBJC_STATIC_FIELD_GETTER(UkCoAmlcurranSocialCoreContainerHelpers, EMPTY_LONGS_, IOSLongArray *)

FOUNDATION_EXPORT IOSObjectArray *UkCoAmlcurranSocialCoreContainerHelpers_EMPTY_OBJECTS_;
J2OBJC_STATIC_FIELD_GETTER(UkCoAmlcurranSocialCoreContainerHelpers, EMPTY_OBJECTS_, IOSObjectArray *)

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_idealIntArraySizeWithInt_(jint need);

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_idealLongArraySizeWithInt_(jint need);

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_idealByteArraySizeWithInt_(jint need);

FOUNDATION_EXPORT jboolean UkCoAmlcurranSocialCoreContainerHelpers_equalWithId_withId_(id a, id b);

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_binarySearchWithIntArray_withInt_withInt_(IOSIntArray *array, jint size, jint value);

FOUNDATION_EXPORT jint UkCoAmlcurranSocialCoreContainerHelpers_binarySearchWithLongArray_withInt_withLong_(IOSLongArray *array, jint size, jlong value);

FOUNDATION_EXPORT void UkCoAmlcurranSocialCoreContainerHelpers_init(UkCoAmlcurranSocialCoreContainerHelpers *self);

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreContainerHelpers *new_UkCoAmlcurranSocialCoreContainerHelpers_init() NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialCoreContainerHelpers)

#endif // _ContainerHelpers_H_
