//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EmptyCalendarItem.java
//

#ifndef _SCEmptyCalendarItem_H_
#define _SCEmptyCalendarItem_H_

#include "J2ObjC_header.h"
#include "uk/co/amlcurran/social/CalendarItem.h"

@protocol SCTime;

@interface SCEmptyCalendarItem : NSObject < SCCalendarItem >

#pragma mark Public

- (instancetype)initWithInt:(jint)position
                 withSCTime:(id<SCTime>)startTime;

- (jboolean)isEmpty;

- (jint)startDay;

- (jlong)startTime;

- (NSString *)title;

@end

J2OBJC_EMPTY_STATIC_INIT(SCEmptyCalendarItem)

FOUNDATION_EXPORT void SCEmptyCalendarItem_initWithInt_withSCTime_(SCEmptyCalendarItem *self, jint position, id<SCTime> startTime);

FOUNDATION_EXPORT SCEmptyCalendarItem *new_SCEmptyCalendarItem_initWithInt_withSCTime_(jint position, id<SCTime> startTime) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(SCEmptyCalendarItem)

typedef SCEmptyCalendarItem UkCoAmlcurranSocialEmptyCalendarItem;

#endif // _SCEmptyCalendarItem_H_
