//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EmptyCalendarItem.java
//

#ifndef _UkCoAmlcurranSocialEmptyCalendarItem_H_
#define _UkCoAmlcurranSocialEmptyCalendarItem_H_

#include "J2ObjC_header.h"
#include "uk/co/amlcurran/social/CalendarItem.h"

@protocol UkCoAmlcurranSocialTime;

@interface UkCoAmlcurranSocialEmptyCalendarItem : NSObject < UkCoAmlcurranSocialCalendarItem >

#pragma mark Public

- (instancetype)initWithInt:(jint)position
withUkCoAmlcurranSocialTime:(id<UkCoAmlcurranSocialTime>)startTime;

- (jboolean)isEmpty;

- (jint)startDay;

- (jlong)startTime;

- (NSString *)title;

@end

J2OBJC_EMPTY_STATIC_INIT(UkCoAmlcurranSocialEmptyCalendarItem)

FOUNDATION_EXPORT void UkCoAmlcurranSocialEmptyCalendarItem_initWithInt_withUkCoAmlcurranSocialTime_(UkCoAmlcurranSocialEmptyCalendarItem *self, jint position, id<UkCoAmlcurranSocialTime> startTime);

FOUNDATION_EXPORT UkCoAmlcurranSocialEmptyCalendarItem *new_UkCoAmlcurranSocialEmptyCalendarItem_initWithInt_withUkCoAmlcurranSocialTime_(jint position, id<UkCoAmlcurranSocialTime> startTime) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialEmptyCalendarItem)

#endif // _UkCoAmlcurranSocialEmptyCalendarItem_H_
