//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EmptyCalendarItem.java
//

#include "EmptyCalendarItem.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "Timestamp.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface SCEmptyCalendarItem () {
 @public
  SCTimestamp *startTime_;
  SCTimestamp *endTime_;
}

@end

J2OBJC_FIELD_SETTER(SCEmptyCalendarItem, startTime_, SCTimestamp *)
J2OBJC_FIELD_SETTER(SCEmptyCalendarItem, endTime_, SCTimestamp *)

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

@implementation SCEmptyCalendarItem

- (instancetype)initWithSCTimestamp:(SCTimestamp *)startTime
                    withSCTimestamp:(SCTimestamp *)endTime {
  SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(self, startTime, endTime);
  return self;
}

- (NSString * __nonnull)title {
  return @"Empty";
}

- (SCTimestamp * __nonnull)startTime {
  return startTime_;
}

- (SCTimestamp * __nonnull)endTime {
  return endTime_;
}

- (jboolean)isEmpty {
  return true;
}

+ (IOSObjectArray *)__annotations_title {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_startTime {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_endTime {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithSCTimestamp:withSCTimestamp:", "EmptyCalendarItem", NULL, 0x1, NULL, NULL },
    { "title", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "startTime", NULL, "Luk.co.amlcurran.social.Timestamp;", 0x1, NULL, NULL },
    { "endTime", NULL, "Luk.co.amlcurran.social.Timestamp;", 0x1, NULL, NULL },
    { "isEmpty", NULL, "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "startTime_", NULL, 0x12, "Luk.co.amlcurran.social.Timestamp;", NULL, NULL, .constantValue.asLong = 0 },
    { "endTime_", NULL, 0x12, "Luk.co.amlcurran.social.Timestamp;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _SCEmptyCalendarItem = { 2, "EmptyCalendarItem", "uk.co.amlcurran.social", NULL, 0x1, 5, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCEmptyCalendarItem;
}

@end

void SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(SCEmptyCalendarItem *self, SCTimestamp *startTime, SCTimestamp *endTime) {
  NSObject_init(self);
  self->startTime_ = startTime;
  self->endTime_ = endTime;
}

SCEmptyCalendarItem *new_SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(SCTimestamp *startTime, SCTimestamp *endTime) {
  SCEmptyCalendarItem *self = [SCEmptyCalendarItem alloc];
  SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(self, startTime, endTime);
  return self;
}

SCEmptyCalendarItem *create_SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(SCTimestamp *startTime, SCTimestamp *endTime) {
  return new_SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(startTime, endTime);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SCEmptyCalendarItem)
