//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EmptyCalendarItem.java
//

#include "EmptyCalendarItem.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "Timestamp.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

@interface SCEmptyCalendarItem () {
 @public
  SCTimestamp *startTime_;
  SCTimestamp *endTime_;
}

@end

J2OBJC_FIELD_SETTER(SCEmptyCalendarItem, startTime_, SCTimestamp *)
J2OBJC_FIELD_SETTER(SCEmptyCalendarItem, endTime_, SCTimestamp *)

__attribute__((unused)) static IOSObjectArray *SCEmptyCalendarItem__Annotations$0();

__attribute__((unused)) static IOSObjectArray *SCEmptyCalendarItem__Annotations$1();

__attribute__((unused)) static IOSObjectArray *SCEmptyCalendarItem__Annotations$2();

@implementation SCEmptyCalendarItem

- (instancetype)initWithSCTimestamp:(SCTimestamp *)startTime
                    withSCTimestamp:(SCTimestamp *)endTime {
  SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(self, startTime, endTime);
  return self;
}

- (NSString * __nonnull)title {
  return @"Empty";
}

- (SCTimestamp * __nonnull)startTime {
  return startTime_;
}

- (SCTimestamp * __nonnull)endTime {
  return endTime_;
}

- (jboolean)isEmpty {
  return true;
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LNSString;", 0x1, -1, -1, -1, -1, 1, -1 },
    { NULL, "LSCTimestamp;", 0x1, -1, -1, -1, -1, 2, -1 },
    { NULL, "LSCTimestamp;", 0x1, -1, -1, -1, -1, 3, -1 },
    { NULL, "Z", 0x1, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(initWithSCTimestamp:withSCTimestamp:);
  methods[1].selector = @selector(title);
  methods[2].selector = @selector(startTime);
  methods[3].selector = @selector(endTime);
  methods[4].selector = @selector(isEmpty);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "startTime_", "LSCTimestamp;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "endTime_", "LSCTimestamp;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "LSCTimestamp;LSCTimestamp;", (void *)&SCEmptyCalendarItem__Annotations$0, (void *)&SCEmptyCalendarItem__Annotations$1, (void *)&SCEmptyCalendarItem__Annotations$2 };
  static const J2ObjcClassInfo _SCEmptyCalendarItem = { "EmptyCalendarItem", "uk.co.amlcurran.social", ptrTable, methods, fields, 7, 0x1, 5, 2, -1, -1, -1, -1, -1 };
  return &_SCEmptyCalendarItem;
}

@end

void SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(SCEmptyCalendarItem *self, SCTimestamp *startTime, SCTimestamp *endTime) {
  NSObject_init(self);
  self->startTime_ = startTime;
  self->endTime_ = endTime;
}

SCEmptyCalendarItem *new_SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(SCTimestamp *startTime, SCTimestamp *endTime) {
  J2OBJC_NEW_IMPL(SCEmptyCalendarItem, initWithSCTimestamp_withSCTimestamp_, startTime, endTime)
}

SCEmptyCalendarItem *create_SCEmptyCalendarItem_initWithSCTimestamp_withSCTimestamp_(SCTimestamp *startTime, SCTimestamp *endTime) {
  J2OBJC_CREATE_IMPL(SCEmptyCalendarItem, initWithSCTimestamp_withSCTimestamp_, startTime, endTime)
}

IOSObjectArray *SCEmptyCalendarItem__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SCEmptyCalendarItem__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SCEmptyCalendarItem__Annotations$2() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SCEmptyCalendarItem)
