//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EmptyCalendarItem.java
//


#include "EmptyCalendarItem.h"
#include "J2ObjC_source.h"
#include "SCTime.h"

@interface SCEmptyCalendarItem () {
 @public
  jint position_;
  id<SCTime> startTime__;
}

@end

J2OBJC_FIELD_SETTER(SCEmptyCalendarItem, startTime__, id<SCTime>)

@implementation SCEmptyCalendarItem

- (instancetype)initWithInt:(jint)position
                 withSCTime:(id<SCTime>)startTime {
  SCEmptyCalendarItem_initWithInt_withSCTime_(self, position, startTime);
  return self;
}

- (NSString *)title {
  return @"Empty";
}

- (jint)startDay {
  return position_;
}

- (jlong)startTime {
  return [((id<SCTime>) nil_chk(startTime__)) getMillis];
}

- (jboolean)isEmpty {
  return YES;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithInt:withSCTime:", "EmptyCalendarItem", NULL, 0x1, NULL, NULL },
    { "title", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "startDay", NULL, "I", 0x1, NULL, NULL },
    { "startTime", NULL, "J", 0x1, NULL, NULL },
    { "isEmpty", NULL, "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "position_", NULL, 0x12, "I", NULL, NULL,  },
    { "startTime__", "startTime", 0x12, "Luk.co.amlcurran.social.Time;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _SCEmptyCalendarItem = { 2, "EmptyCalendarItem", "uk.co.amlcurran.social", NULL, 0x1, 5, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCEmptyCalendarItem;
}

@end

void SCEmptyCalendarItem_initWithInt_withSCTime_(SCEmptyCalendarItem *self, jint position, id<SCTime> startTime) {
  (void) NSObject_init(self);
  self->position_ = position;
  self->startTime__ = startTime;
}

SCEmptyCalendarItem *new_SCEmptyCalendarItem_initWithInt_withSCTime_(jint position, id<SCTime> startTime) {
  SCEmptyCalendarItem *self = [SCEmptyCalendarItem alloc];
  SCEmptyCalendarItem_initWithInt_withSCTime_(self, position, startTime);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SCEmptyCalendarItem)
