//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventsService.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EventsService")
#ifdef RESTRICT_EventsService
#define INCLUDE_ALL_EventsService 0
#else
#define INCLUDE_ALL_EventsService 1
#endif
#undef RESTRICT_EventsService

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SCEventsService_) && (INCLUDE_ALL_EventsService || defined(INCLUDE_SCEventsService))
#define SCEventsService_

@class SCCalendarSource;
@class SCTimestamp;
@protocol SCEventsRepository;
@protocol SCTimeCalculator;
@protocol SCTimeRepository;

@interface SCEventsService : NSObject

#pragma mark Public

- (instancetype)initWithSCTimeRepository:(id<SCTimeRepository>)dateCreator
                  withSCEventsRepository:(id<SCEventsRepository>)eventsRepository
                    withSCTimeCalculator:(id<SCTimeCalculator>)timeCalculator;

- (SCCalendarSource * __nonnull)getCalendarSourceWithInt:(jint)numberOfDays
                                         withSCTimestamp:(SCTimestamp *)now;

@end

J2OBJC_EMPTY_STATIC_INIT(SCEventsService)

FOUNDATION_EXPORT void SCEventsService_initWithSCTimeRepository_withSCEventsRepository_withSCTimeCalculator_(SCEventsService *self, id<SCTimeRepository> dateCreator, id<SCEventsRepository> eventsRepository, id<SCTimeCalculator> timeCalculator);

FOUNDATION_EXPORT SCEventsService *new_SCEventsService_initWithSCTimeRepository_withSCEventsRepository_withSCTimeCalculator_(id<SCTimeRepository> dateCreator, id<SCEventsRepository> eventsRepository, id<SCTimeCalculator> timeCalculator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SCEventsService *create_SCEventsService_initWithSCTimeRepository_withSCEventsRepository_withSCTimeCalculator_(id<SCTimeRepository> dateCreator, id<SCEventsRepository> eventsRepository, id<SCTimeCalculator> timeCalculator);

J2OBJC_TYPE_LITERAL_HEADER(SCEventsService)

@compatibility_alias UkCoAmlcurranSocialEventsService SCEventsService;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_EventsService")
