//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventsService.java
//

#include "CalendarItem.h"
#include "CalendarSlot.h"
#include "CalendarSource.h"
#include "EventsRepository.h"
#include "EventsService.h"
#include "J2ObjC_source.h"
#include "SparseArray.h"
#include "TimeOfDay.h"
#include "TimeRepository.h"
#include "Timestamp.h"
#include "java/util/List.h"

@interface SCEventsService () {
 @public
  id<SCTimeRepository> timeRepository_;
  id<SCEventsRepository> eventsRepository_;
}

@end

J2OBJC_FIELD_SETTER(SCEventsService, timeRepository_, id<SCTimeRepository>)
J2OBJC_FIELD_SETTER(SCEventsService, eventsRepository_, id<SCEventsRepository>)

@implementation SCEventsService

- (instancetype)initWithSCTimeRepository:(id<SCTimeRepository>)dateCreator
                  withSCEventsRepository:(id<SCEventsRepository>)eventsRepository {
  SCEventsService_initWithSCTimeRepository_withSCEventsRepository_(self, dateCreator, eventsRepository);
  return self;
}

- (SCCalendarSource *)getCalendarSourceWithInt:(jint)numberOfDays
                               withSCTimestamp:(SCTimestamp *)now {
  SCTimestamp *nowTime = [((id<SCTimeRepository>) nil_chk(timeRepository_)) startOfToday];
  SCTimestamp *nextWeek = [((SCTimestamp *) nil_chk(nowTime)) plusDaysWithInt:numberOfDays];
  SCTimeOfDay *fivePm = [timeRepository_ borderTimeStart];
  SCTimeOfDay *elevenPm = [timeRepository_ borderTimeEnd];
  id<JavaUtilList> calendarItems = [((id<SCEventsRepository>) nil_chk(eventsRepository_)) getCalendarItemsWithSCTimestamp:nowTime withSCTimestamp:nextWeek withSCTimeOfDay:fivePm withSCTimeOfDay:elevenPm withSCEventsService:self];
  UkCoAmlcurranSocialCoreSparseArray *itemArray = new_UkCoAmlcurranSocialCoreSparseArray_initWithInt_(numberOfDays);
  jint epochToNow = [((SCTimestamp *) nil_chk(now)) daysSinceEpoch];
  for (id<SCCalendarItem> __strong item in nil_chk(calendarItems)) {
    jint key = [((SCTimestamp *) nil_chk([((id<SCCalendarItem>) nil_chk(item)) startTime])) daysSinceEpoch] - epochToNow;
    SCCalendarSlot *slot = [itemArray getWithInt:key withId:new_SCCalendarSlot_init()];
    [((SCCalendarSlot *) nil_chk(slot)) addItemWithSCCalendarItem:item];
    [itemArray putWithInt:key withId:slot];
  }
  return new_SCCalendarSource_initWithSCTimeRepository_withUkCoAmlcurranSocialCoreSparseArray_withInt_(timeRepository_, itemArray, numberOfDays);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithSCTimeRepository:withSCEventsRepository:", "EventsService", NULL, 0x1, NULL, NULL },
    { "getCalendarSourceWithInt:withSCTimestamp:", "getCalendarSource", "Luk.co.amlcurran.social.CalendarSource;", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "timeRepository_", NULL, 0x12, "Luk.co.amlcurran.social.TimeRepository;", NULL, NULL, .constantValue.asLong = 0 },
    { "eventsRepository_", NULL, 0x12, "Luk.co.amlcurran.social.EventsRepository;", NULL, NULL, .constantValue.asLong = 0 },
  };
  static const J2ObjcClassInfo _SCEventsService = { 2, "EventsService", "uk.co.amlcurran.social", NULL, 0x1, 2, methods, 2, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCEventsService;
}

@end

void SCEventsService_initWithSCTimeRepository_withSCEventsRepository_(SCEventsService *self, id<SCTimeRepository> dateCreator, id<SCEventsRepository> eventsRepository) {
  NSObject_init(self);
  self->eventsRepository_ = eventsRepository;
  self->timeRepository_ = dateCreator;
}

SCEventsService *new_SCEventsService_initWithSCTimeRepository_withSCEventsRepository_(id<SCTimeRepository> dateCreator, id<SCEventsRepository> eventsRepository) {
  SCEventsService *self = [SCEventsService alloc];
  SCEventsService_initWithSCTimeRepository_withSCEventsRepository_(self, dateCreator, eventsRepository);
  return self;
}

SCEventsService *create_SCEventsService_initWithSCTimeRepository_withSCEventsRepository_(id<SCTimeRepository> dateCreator, id<SCEventsRepository> eventsRepository) {
  return new_SCEventsService_initWithSCTimeRepository_withSCEventsRepository_(dateCreator, eventsRepository);
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SCEventsService)
