//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventCalendarItem.java
//

#ifndef _UkCoAmlcurranSocialEventCalendarItem_H_
#define _UkCoAmlcurranSocialEventCalendarItem_H_

#include "J2ObjC_header.h"
#include "uk/co/amlcurran/social/CalendarItem.h"

@protocol UkCoAmlcurranSocialTime;

@interface UkCoAmlcurranSocialEventCalendarItem : NSObject < UkCoAmlcurranSocialCalendarItem >

#pragma mark Public

- (instancetype)initWithLong:(jlong)eventId
                withNSString:(NSString *)title
                    withLong:(jlong)startTime
 withUkCoAmlcurranSocialTime:(id<UkCoAmlcurranSocialTime>)time;

- (jlong)id__;

- (jboolean)isEmpty;

- (jint)startDay;

- (jlong)startTime;

- (NSString *)title;

@end

J2OBJC_EMPTY_STATIC_INIT(UkCoAmlcurranSocialEventCalendarItem)

FOUNDATION_EXPORT void UkCoAmlcurranSocialEventCalendarItem_initWithLong_withNSString_withLong_withUkCoAmlcurranSocialTime_(UkCoAmlcurranSocialEventCalendarItem *self, jlong eventId, NSString *title, jlong startTime, id<UkCoAmlcurranSocialTime> time);

FOUNDATION_EXPORT UkCoAmlcurranSocialEventCalendarItem *new_UkCoAmlcurranSocialEventCalendarItem_initWithLong_withNSString_withLong_withUkCoAmlcurranSocialTime_(jlong eventId, NSString *title, jlong startTime, id<UkCoAmlcurranSocialTime> time) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialEventCalendarItem)

#endif // _UkCoAmlcurranSocialEventCalendarItem_H_
