//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventRepositoryAccessor.java
//

#include "EventRepositoryAccessor.h"
#include "J2ObjC_source.h"
#include "Time.h"

@interface SCEventRepositoryAccessor : NSObject

@end

@implementation SCEventRepositoryAccessor

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getTitle", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "getEventIdentifier", NULL, "Ljava.lang.String;", 0x401, NULL, NULL },
    { "nextItem", NULL, "Z", 0x401, NULL, NULL },
    { "endAccess", NULL, "V", 0x401, NULL, NULL },
    { "getStartTime", NULL, "Luk.co.amlcurran.social.Time;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _SCEventRepositoryAccessor = { 2, "EventRepositoryAccessor", "uk.co.amlcurran.social", NULL, 0x609, 5, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCEventRepositoryAccessor;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCEventRepositoryAccessor)
