//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventsRepository.java
//

#include "EventRepositoryAccessor.h"
#include "EventsRepository.h"
#include "J2ObjC_source.h"
#include "SCTime.h"

@interface SCEventsRepository : NSObject

@end

@implementation SCEventsRepository

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "queryEventsWithLong:withLong:withSCTime:withSCTime:", "queryEvents", "Luk.co.amlcurran.social.EventRepositoryAccessor;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _SCEventsRepository = { 2, "EventsRepository", "uk.co.amlcurran.social", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCEventsRepository;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCEventsRepository)
