//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventsRepository.java
//

#include "EventsRepository.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "TimeOfDay.h"
#include "Timestamp.h"
#include "java/util/List.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface SCEventsRepository : NSObject

@end

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

@implementation SCEventsRepository

+ (IOSObjectArray *)__annotations_getCalendarItemsWithSCTimestamp_withSCTimestamp_withSCTimeOfDay_withSCTimeOfDay_ {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getCalendarItemsWithSCTimestamp:withSCTimestamp:withSCTimeOfDay:withSCTimeOfDay:", "getCalendarItems", "Ljava.util.List;", 0x401, NULL, "(Luk/co/amlcurran/social/Timestamp;Luk/co/amlcurran/social/Timestamp;Luk/co/amlcurran/social/TimeOfDay;Luk/co/amlcurran/social/TimeOfDay;)Ljava/util/List<Luk/co/amlcurran/social/CalendarItem;>;" },
  };
  static const J2ObjcClassInfo _SCEventsRepository = { 2, "EventsRepository", "uk.co.amlcurran.social", NULL, 0x609, 1, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCEventsRepository;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCEventsRepository)
