//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventsRepository.java
//

#include "J2ObjC_header.h"

#pragma push_macro("EventsRepository_INCLUDE_ALL")
#ifdef EventsRepository_RESTRICT
#define EventsRepository_INCLUDE_ALL 0
#else
#define EventsRepository_INCLUDE_ALL 1
#endif
#undef EventsRepository_RESTRICT

#if !defined (SCEventsRepository_) && (EventsRepository_INCLUDE_ALL || defined(SCEventsRepository_INCLUDE))
#define SCEventsRepository_

@class SCTimeOfDay;
@class SCTimestamp;
@protocol SCEventRepositoryAccessor;

@protocol SCEventsRepository < NSObject, JavaObject >

- (id<SCEventRepositoryAccessor>)queryEventsWithSCTimeOfDay:(SCTimeOfDay *)fivePm
                                            withSCTimeOfDay:(SCTimeOfDay *)elevenPm
                                            withSCTimestamp:(SCTimestamp *)searchStartTime
                                            withSCTimestamp:(SCTimestamp *)searchEndTime;

@end

J2OBJC_EMPTY_STATIC_INIT(SCEventsRepository)

J2OBJC_TYPE_LITERAL_HEADER(SCEventsRepository)

#define UkCoAmlcurranSocialEventsRepository SCEventsRepository

#endif

#pragma pop_macro("EventsRepository_INCLUDE_ALL")
