//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventsRepository.java
//

#include "EventsRepository.h"
#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

@interface SCEventsRepository : NSObject

@end

__attribute__((unused)) static IOSObjectArray *SCEventsRepository__Annotations$0();

@implementation SCEventsRepository

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LJavaUtilList;", 0x401, 0, 1, -1, 2, 3, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(getCalendarItemsWithSCTimestamp:withSCTimestamp:withSCTimeOfDay:withSCTimeOfDay:);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "getCalendarItems", "LSCTimestamp;LSCTimestamp;LSCTimeOfDay;LSCTimeOfDay;", "(Luk/co/amlcurran/social/Timestamp;Luk/co/amlcurran/social/Timestamp;Luk/co/amlcurran/social/TimeOfDay;Luk/co/amlcurran/social/TimeOfDay;)Ljava/util/List<Luk/co/amlcurran/social/CalendarItem;>;", (void *)&SCEventsRepository__Annotations$0 };
  static const J2ObjcClassInfo _SCEventsRepository = { "EventsRepository", "uk.co.amlcurran.social", ptrTable, methods, NULL, 7, 0x609, 1, 0, -1, -1, -1, -1, -1 };
  return &_SCEventsRepository;
}

@end

IOSObjectArray *SCEventsRepository__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCEventsRepository)
