//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventCalendarItem.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_EventCalendarItem")
#ifdef RESTRICT_EventCalendarItem
#define INCLUDE_ALL_EventCalendarItem 0
#else
#define INCLUDE_ALL_EventCalendarItem 1
#endif
#undef RESTRICT_EventCalendarItem

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SCEventCalendarItem_) && (INCLUDE_ALL_EventCalendarItem || defined(INCLUDE_SCEventCalendarItem))
#define SCEventCalendarItem_

#define RESTRICT_CalendarItem 1
#define INCLUDE_SCCalendarItem 1
#include "CalendarItem.h"

@class SCTimestamp;

@interface SCEventCalendarItem : NSObject < SCCalendarItem >

#pragma mark Public

- (instancetype __nonnull)initWithNSString:(NSString *)eventId
                              withNSString:(NSString *)title
                           withSCTimestamp:(SCTimestamp *)time
                           withSCTimestamp:(SCTimestamp *)endTime;

- (SCTimestamp * __nonnull)endTime;

- (NSString *)id__;

- (jboolean)isEmpty;

- (SCTimestamp * __nonnull)startTime;

- (NSString * __nonnull)title;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(SCEventCalendarItem)

FOUNDATION_EXPORT void SCEventCalendarItem_initWithNSString_withNSString_withSCTimestamp_withSCTimestamp_(SCEventCalendarItem *self, NSString *eventId, NSString *title, SCTimestamp *time, SCTimestamp *endTime);

FOUNDATION_EXPORT SCEventCalendarItem *new_SCEventCalendarItem_initWithNSString_withNSString_withSCTimestamp_withSCTimestamp_(NSString *eventId, NSString *title, SCTimestamp *time, SCTimestamp *endTime) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT SCEventCalendarItem *create_SCEventCalendarItem_initWithNSString_withNSString_withSCTimestamp_withSCTimestamp_(NSString *eventId, NSString *title, SCTimestamp *time, SCTimestamp *endTime);

J2OBJC_TYPE_LITERAL_HEADER(SCEventCalendarItem)

@compatibility_alias UkCoAmlcurranSocialEventCalendarItem SCEventCalendarItem;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_EventCalendarItem")
