//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventsRepository.java
//

#include "J2ObjC_header.h"

#pragma push_macro("EventsRepository_INCLUDE_ALL")
#ifdef EventsRepository_RESTRICT
#define EventsRepository_INCLUDE_ALL 0
#else
#define EventsRepository_INCLUDE_ALL 1
#endif
#undef EventsRepository_RESTRICT

#if !defined (SCEventsRepository_) && (EventsRepository_INCLUDE_ALL || defined(SCEventsRepository_INCLUDE))
#define SCEventsRepository_

@class SCEventsService;
@class SCTimeOfDay;
@class SCTimestamp;
@protocol JavaUtilList;

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@protocol SCEventsRepository < NSObject, JavaObject >

- (id<JavaUtilList> __nonnull)getCalendarItemsWithSCTimestamp:(SCTimestamp *)nowTime
                                              withSCTimestamp:(SCTimestamp *)nextWeek
                                              withSCTimeOfDay:(SCTimeOfDay *)fivePm
                                              withSCTimeOfDay:(SCTimeOfDay *)elevenPm
                                          withSCEventsService:(SCEventsService *)eventsService;

@end

J2OBJC_EMPTY_STATIC_INIT(SCEventsRepository)

J2OBJC_TYPE_LITERAL_HEADER(SCEventsRepository)

#define UkCoAmlcurranSocialEventsRepository SCEventsRepository

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif

#pragma pop_macro("EventsRepository_INCLUDE_ALL")
