//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventRepositoryAccessor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("EventRepositoryAccessor_INCLUDE_ALL")
#ifdef EventRepositoryAccessor_RESTRICT
#define EventRepositoryAccessor_INCLUDE_ALL 0
#else
#define EventRepositoryAccessor_INCLUDE_ALL 1
#endif
#undef EventRepositoryAccessor_RESTRICT

#if !defined (SCEventRepositoryAccessor_) && (EventRepositoryAccessor_INCLUDE_ALL || defined(SCEventRepositoryAccessor_INCLUDE))
#define SCEventRepositoryAccessor_

@class SCTimestamp;

@protocol SCEventRepositoryAccessor < NSObject, JavaObject >

- (NSString *)getTitle;

- (NSString *)getEventIdentifier;

- (jboolean)nextItem;

- (void)endAccess;

- (SCTimestamp *)getStartTime;

- (SCTimestamp *)getEndTime;

@end

J2OBJC_EMPTY_STATIC_INIT(SCEventRepositoryAccessor)

J2OBJC_TYPE_LITERAL_HEADER(SCEventRepositoryAccessor)

#define UkCoAmlcurranSocialEventRepositoryAccessor SCEventRepositoryAccessor

#endif

#pragma pop_macro("EventRepositoryAccessor_INCLUDE_ALL")
