//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventsService.java
//

#ifndef _UkCoAmlcurranSocialEventsService_H_
#define _UkCoAmlcurranSocialEventsService_H_

#include "J2ObjC_header.h"

@class UkCoAmlcurranSocialCalendarSource;
@protocol UkCoAmlcurranSocialEventsRepository;
@protocol UkCoAmlcurranSocialTime;
@protocol UkCoAmlcurranSocialTimeRepository;

@interface UkCoAmlcurranSocialEventsService : NSObject

#pragma mark Public

- (instancetype)initWithUkCoAmlcurranSocialTimeRepository:(id<UkCoAmlcurranSocialTimeRepository>)dateCreator
                  withUkCoAmlcurranSocialEventsRepository:(id<UkCoAmlcurranSocialEventsRepository>)eventsRepository;

- (UkCoAmlcurranSocialCalendarSource *)getCalendarSourceWithInt:(jint)numberOfDays
                                    withUkCoAmlcurranSocialTime:(id<UkCoAmlcurranSocialTime>)now;

@end

J2OBJC_EMPTY_STATIC_INIT(UkCoAmlcurranSocialEventsService)

FOUNDATION_EXPORT void UkCoAmlcurranSocialEventsService_initWithUkCoAmlcurranSocialTimeRepository_withUkCoAmlcurranSocialEventsRepository_(UkCoAmlcurranSocialEventsService *self, id<UkCoAmlcurranSocialTimeRepository> dateCreator, id<UkCoAmlcurranSocialEventsRepository> eventsRepository);

FOUNDATION_EXPORT UkCoAmlcurranSocialEventsService *new_UkCoAmlcurranSocialEventsService_initWithUkCoAmlcurranSocialTimeRepository_withUkCoAmlcurranSocialEventsRepository_(id<UkCoAmlcurranSocialTimeRepository> dateCreator, id<UkCoAmlcurranSocialEventsRepository> eventsRepository) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialEventsService)

#endif // _UkCoAmlcurranSocialEventsService_H_
