//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/EventCalendarItem.java
//


#include "EventCalendarItem.h"
#include "J2ObjC_source.h"
#include "ScTime.h"

@interface SCEventCalendarItem () {
 @public
  jlong eventId_;
  NSString *title__;
  jlong startTime__;
  id<SCTime> start_;
}

@end

J2OBJC_FIELD_SETTER(SCEventCalendarItem, title__, NSString *)
J2OBJC_FIELD_SETTER(SCEventCalendarItem, start_, id<SCTime>)

@implementation SCEventCalendarItem

- (instancetype)initWithLong:(jlong)eventId
                withNSString:(NSString *)title
                    withLong:(jlong)startTime
                  withSCTime:(id<SCTime>)time {
  SCEventCalendarItem_initWithLong_withNSString_withLong_withSCTime_(self, eventId, title, startTime, time);
  return self;
}

- (jlong)id__ {
  return eventId_;
}

- (NSString *)title {
  return title__;
}

- (jint)startDay {
  return [((id<SCTime>) nil_chk(start_)) daysSinceEpoch];
}

- (jlong)startTime {
  return startTime__;
}

- (jboolean)isEmpty {
  return NO;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithLong:withNSString:withLong:withSCTime:", "EventCalendarItem", NULL, 0x1, NULL, NULL },
    { "id__", "id", "J", 0x1, NULL, NULL },
    { "title", NULL, "Ljava.lang.String;", 0x1, NULL, NULL },
    { "startDay", NULL, "I", 0x1, NULL, NULL },
    { "startTime", NULL, "J", 0x1, NULL, NULL },
    { "isEmpty", NULL, "Z", 0x1, NULL, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "eventId_", NULL, 0x12, "J", NULL, NULL,  },
    { "title__", "title", 0x12, "Ljava.lang.String;", NULL, NULL,  },
    { "startTime__", "startTime", 0x12, "J", NULL, NULL,  },
    { "start_", NULL, 0x12, "Luk.co.amlcurran.social.Time;", NULL, NULL,  },
  };
  static const J2ObjcClassInfo _SCEventCalendarItem = { 2, "EventCalendarItem", "uk.co.amlcurran.social", NULL, 0x0, 6, methods, 4, fields, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCEventCalendarItem;
}

@end

void SCEventCalendarItem_initWithLong_withNSString_withLong_withSCTime_(SCEventCalendarItem *self, jlong eventId, NSString *title, jlong startTime, id<SCTime> time) {
  (void) NSObject_init(self);
  self->eventId_ = eventId;
  self->title__ = title;
  self->startTime__ = startTime;
  self->start_ = time;
}

SCEventCalendarItem *new_SCEventCalendarItem_initWithLong_withNSString_withLong_withSCTime_(jlong eventId, NSString *title, jlong startTime, id<SCTime> time) {
  SCEventCalendarItem *self = [SCEventCalendarItem alloc];
  SCEventCalendarItem_initWithLong_withNSString_withLong_withSCTime_(self, eventId, title, startTime, time);
  return self;
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SCEventCalendarItem)
