//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/Time.java
//

#ifndef _Time_H_
#define _Time_H_

#include "J2ObjC_header.h"

@protocol SCTimeCalculator;

@interface SCTime : NSObject

#pragma mark Public

- (instancetype)initWithLong:(jlong)millis
        withSCTimeCalculator:(id<SCTimeCalculator>)timeCalculator;

- (jint)daysSinceEpoch;

- (jlong)getMillis;

- (SCTime *)plusDaysWithInt:(jint)days;

- (SCTime *)plusHoursWithInt:(jint)hours;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTime)

FOUNDATION_EXPORT void SCTime_initWithLong_withSCTimeCalculator_(SCTime *self, jlong millis, id<SCTimeCalculator> timeCalculator);

FOUNDATION_EXPORT SCTime *new_SCTime_initWithLong_withSCTimeCalculator_(jlong millis, id<SCTimeCalculator> timeCalculator) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(SCTime)

@compatibility_alias UkCoAmlcurranSocialTime SCTime;

#endif // _Time_H_
