//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/core/SparseArray.java
//

#ifndef _UkCoAmlcurranSocialCoreSparseArray_H_
#define _UkCoAmlcurranSocialCoreSparseArray_H_

#include "J2ObjC_header.h"

@interface UkCoAmlcurranSocialCoreSparseArray : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)initialCapacity;

- (void)appendWithInt:(jint)key
               withId:(id)value;

- (void)clear;

- (UkCoAmlcurranSocialCoreSparseArray *)clone;

- (void)delete__WithInt:(jint)key;

- (id)getWithInt:(jint)key;

- (id)getWithInt:(jint)key
          withId:(id)valueIfKeyNotFound;

- (jint)indexOfKeyWithInt:(jint)key;

- (jint)indexOfValueWithId:(id)value;

- (jint)keyAtWithInt:(jint)index;

- (void)putWithInt:(jint)key
            withId:(id)value;

- (void)removeWithInt:(jint)key;

- (void)removeAtWithInt:(jint)index;

- (void)removeAtRangeWithInt:(jint)index
                     withInt:(jint)size;

- (void)setValueAtWithInt:(jint)index
                   withId:(id)value;

- (jint)size;

- (NSString *)description;

- (id)valueAtWithInt:(jint)index;

@end

J2OBJC_STATIC_INIT(UkCoAmlcurranSocialCoreSparseArray)

FOUNDATION_EXPORT void UkCoAmlcurranSocialCoreSparseArray_init(UkCoAmlcurranSocialCoreSparseArray *self);

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreSparseArray *new_UkCoAmlcurranSocialCoreSparseArray_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT void UkCoAmlcurranSocialCoreSparseArray_initWithInt_(UkCoAmlcurranSocialCoreSparseArray *self, jint initialCapacity);

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreSparseArray *new_UkCoAmlcurranSocialCoreSparseArray_initWithInt_(jint initialCapacity) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialCoreSparseArray)

#endif // _UkCoAmlcurranSocialCoreSparseArray_H_
