//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/core/SparseArray.java
//

#include "J2ObjC_header.h"

#pragma push_macro("SparseArray_INCLUDE_ALL")
#ifdef SparseArray_RESTRICT
#define SparseArray_INCLUDE_ALL 0
#else
#define SparseArray_INCLUDE_ALL 1
#endif
#undef SparseArray_RESTRICT

#if !defined (UkCoAmlcurranSocialCoreSparseArray_) && (SparseArray_INCLUDE_ALL || defined(UkCoAmlcurranSocialCoreSparseArray_INCLUDE))
#define UkCoAmlcurranSocialCoreSparseArray_

@interface UkCoAmlcurranSocialCoreSparseArray : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)initialCapacity;

- (void)appendWithInt:(jint)key
               withId:(id)value;

- (void)clear;

- (UkCoAmlcurranSocialCoreSparseArray *)clone;

- (void)delete__WithInt:(jint)key;

- (id)getWithInt:(jint)key;

- (id)getWithInt:(jint)key
          withId:(id)valueIfKeyNotFound;

- (jint)indexOfKeyWithInt:(jint)key;

- (jint)indexOfValueWithId:(id)value;

- (jint)keyAtWithInt:(jint)index;

- (void)putWithInt:(jint)key
            withId:(id)value;

- (void)removeWithInt:(jint)key;

- (void)removeAtWithInt:(jint)index;

- (void)removeAtRangeWithInt:(jint)index
                     withInt:(jint)size;

- (void)setValueAtWithInt:(jint)index
                   withId:(id)value;

- (jint)size;

- (NSString *)description;

- (id)valueAtWithInt:(jint)index;

@end

J2OBJC_STATIC_INIT(UkCoAmlcurranSocialCoreSparseArray)

FOUNDATION_EXPORT void UkCoAmlcurranSocialCoreSparseArray_init(UkCoAmlcurranSocialCoreSparseArray *self);

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreSparseArray *new_UkCoAmlcurranSocialCoreSparseArray_init() NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreSparseArray *create_UkCoAmlcurranSocialCoreSparseArray_init();

FOUNDATION_EXPORT void UkCoAmlcurranSocialCoreSparseArray_initWithInt_(UkCoAmlcurranSocialCoreSparseArray *self, jint initialCapacity);

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreSparseArray *new_UkCoAmlcurranSocialCoreSparseArray_initWithInt_(jint initialCapacity) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkCoAmlcurranSocialCoreSparseArray *create_UkCoAmlcurranSocialCoreSparseArray_initWithInt_(jint initialCapacity);

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialCoreSparseArray)

#endif

#pragma pop_macro("SparseArray_INCLUDE_ALL")
