//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/utils/SparseArray.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_SparseArray")
#ifdef RESTRICT_SparseArray
#define INCLUDE_ALL_SparseArray 0
#else
#define INCLUDE_ALL_SparseArray 1
#endif
#undef RESTRICT_SparseArray

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (UkCoAmlcurranSocialUtilsSparseArray_) && (INCLUDE_ALL_SparseArray || defined(INCLUDE_UkCoAmlcurranSocialUtilsSparseArray))
#define UkCoAmlcurranSocialUtilsSparseArray_

@interface UkCoAmlcurranSocialUtilsSparseArray : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (instancetype __nonnull)initWithInt:(jint)initialCapacity;

- (void)appendWithInt:(jint)key
               withId:(id)value;

- (void)clear;

- (UkCoAmlcurranSocialUtilsSparseArray *)java_clone;

- (void)delete__WithInt:(jint)key;

- (id)getWithInt:(jint)key;

- (id)getWithInt:(jint)key
          withId:(id)valueIfKeyNotFound;

- (jint)indexOfKeyWithInt:(jint)key;

- (jint)indexOfValueWithId:(id)value;

- (jint)keyAtWithInt:(jint)index;

- (void)putWithInt:(jint)key
            withId:(id)value;

- (void)removeWithInt:(jint)key;

- (void)removeAtWithInt:(jint)index;

- (void)removeAtRangeWithInt:(jint)index
                     withInt:(jint)size;

- (void)setValueAtWithInt:(jint)index
                   withId:(id)value;

- (jint)size;

- (NSString *)description;

- (id)valueAtWithInt:(jint)index;

@end

J2OBJC_STATIC_INIT(UkCoAmlcurranSocialUtilsSparseArray)

FOUNDATION_EXPORT void UkCoAmlcurranSocialUtilsSparseArray_init(UkCoAmlcurranSocialUtilsSparseArray *self);

FOUNDATION_EXPORT UkCoAmlcurranSocialUtilsSparseArray *new_UkCoAmlcurranSocialUtilsSparseArray_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkCoAmlcurranSocialUtilsSparseArray *create_UkCoAmlcurranSocialUtilsSparseArray_init(void);

FOUNDATION_EXPORT void UkCoAmlcurranSocialUtilsSparseArray_initWithInt_(UkCoAmlcurranSocialUtilsSparseArray *self, jint initialCapacity);

FOUNDATION_EXPORT UkCoAmlcurranSocialUtilsSparseArray *new_UkCoAmlcurranSocialUtilsSparseArray_initWithInt_(jint initialCapacity) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT UkCoAmlcurranSocialUtilsSparseArray *create_UkCoAmlcurranSocialUtilsSparseArray_initWithInt_(jint initialCapacity);

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialUtilsSparseArray)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_SparseArray")
