//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeCalculator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("TimeCalculator_INCLUDE_ALL")
#ifdef TimeCalculator_RESTRICT
#define TimeCalculator_INCLUDE_ALL 0
#else
#define TimeCalculator_INCLUDE_ALL 1
#endif
#undef TimeCalculator_RESTRICT

#if !defined (SCTimeCalculator_) && (TimeCalculator_INCLUDE_ALL || defined(SCTimeCalculator_INCLUDE))
#define SCTimeCalculator_

@class SCTimestamp;

@protocol SCTimeCalculator < NSObject, JavaObject >

- (SCTimestamp *)plusDaysWithInt:(jint)days
                 withSCTimestamp:(SCTimestamp *)time;

- (jint)getDaysWithSCTimestamp:(SCTimestamp *)time;

- (SCTimestamp *)plusHoursWithSCTimestamp:(SCTimestamp *)time
                                  withInt:(jint)hours;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTimeCalculator)

J2OBJC_TYPE_LITERAL_HEADER(SCTimeCalculator)

#define UkCoAmlcurranSocialTimeCalculator SCTimeCalculator

#endif

#pragma pop_macro("TimeCalculator_INCLUDE_ALL")
