//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeCalculator.java
//

#include "J2ObjC_source.h"
#include "SCTime.h"
#include "TimeCalculator.h"

@interface SCTimeCalculator : NSObject

@end

@implementation SCTimeCalculator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "plusDaysWithInt:withSCTime:", "plusDays", "Luk.co.amlcurran.social.Time;", 0x401, NULL, NULL },
    { "getDaysWithSCTime:", "getDays", "I", 0x401, NULL, NULL },
    { "plusHoursWithSCTime:withInt:", "plusHours", "Luk.co.amlcurran.social.Time;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _SCTimeCalculator = { 2, "TimeCalculator", "uk.co.amlcurran.social", NULL, 0x609, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCTimeCalculator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCTimeCalculator)
