//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeRepository.java
//

#ifndef _UkCoAmlcurranSocialTimeRepository_H_
#define _UkCoAmlcurranSocialTimeRepository_H_

#include "J2ObjC_header.h"

@protocol UkCoAmlcurranSocialTime;

@protocol UkCoAmlcurranSocialTimeRepository < NSObject, JavaObject >

- (jint)endOfBorderTimeInMinutes;

- (jint)startOfBorderTimeInMinutes;

- (id<UkCoAmlcurranSocialTime>)startOfToday;

@end

J2OBJC_EMPTY_STATIC_INIT(UkCoAmlcurranSocialTimeRepository)

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialTimeRepository)

#endif // _UkCoAmlcurranSocialTimeRepository_H_
