//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeRepository.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "TimeOfDay.h"
#include "TimeRepository.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface SCTimeRepository : NSObject

@end

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

@implementation SCTimeRepository

+ (IOSObjectArray *)__annotations_borderTimeEnd {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (IOSObjectArray *)__annotations_borderTimeStart {
  return [IOSObjectArray arrayWithObjects:(id[]) { [[JavaxAnnotationNonnull alloc] initWithWhen:JavaxAnnotationMetaWhen_get_ALWAYS()] } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "borderTimeEnd", NULL, "Luk.co.amlcurran.social.TimeOfDay;", 0x401, NULL, NULL },
    { "borderTimeStart", NULL, "Luk.co.amlcurran.social.TimeOfDay;", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _SCTimeRepository = { 2, "TimeRepository", "uk.co.amlcurran.social", NULL, 0x609, 2, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCTimeRepository;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCTimeRepository)
