//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeOfDay.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TimeOfDay")
#ifdef RESTRICT_TimeOfDay
#define INCLUDE_ALL_TimeOfDay 0
#else
#define INCLUDE_ALL_TimeOfDay 1
#endif
#undef RESTRICT_TimeOfDay

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SCTimeOfDay_) && (INCLUDE_ALL_TimeOfDay || defined(INCLUDE_SCTimeOfDay))
#define SCTimeOfDay_

@interface SCTimeOfDay : NSObject

#pragma mark Public

+ (SCTimeOfDay * __nonnull)fromHoursWithInt:(jint)hours;

+ (SCTimeOfDay * __nonnull)fromHoursAndMinuteWithInt:(jint)hours
                                             withInt:(jint)minutes;

- (jlong)hoursInDay;

- (jlong)minutesInDay;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTimeOfDay)

FOUNDATION_EXPORT SCTimeOfDay *SCTimeOfDay_fromHoursWithInt_(jint hours);

FOUNDATION_EXPORT SCTimeOfDay *SCTimeOfDay_fromHoursAndMinuteWithInt_withInt_(jint hours, jint minutes);

J2OBJC_TYPE_LITERAL_HEADER(SCTimeOfDay)

@compatibility_alias UkCoAmlcurranSocialTimeOfDay SCTimeOfDay;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_TimeOfDay")
