//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeCalculator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_TimeCalculator")
#ifdef RESTRICT_TimeCalculator
#define INCLUDE_ALL_TimeCalculator 0
#else
#define INCLUDE_ALL_TimeCalculator 1
#endif
#undef RESTRICT_TimeCalculator

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (SCTimeCalculator_) && (INCLUDE_ALL_TimeCalculator || defined(INCLUDE_SCTimeCalculator))
#define SCTimeCalculator_

@class SCTimestamp;

@protocol SCTimeCalculator < JavaObject >

- (SCTimestamp * __nonnull)plusDaysWithInt:(jint)days
                           withSCTimestamp:(SCTimestamp *)time;

- (jint)getDaysWithSCTimestamp:(SCTimestamp *)time;

- (SCTimestamp * __nonnull)plusHoursWithSCTimestamp:(SCTimestamp *)time
                                            withInt:(jint)hours;

- (SCTimestamp *)startOfToday;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTimeCalculator)

J2OBJC_TYPE_LITERAL_HEADER(SCTimeCalculator)

#define UkCoAmlcurranSocialTimeCalculator SCTimeCalculator

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_TimeCalculator")
