//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/Time.java
//

#ifndef _SCTime_H_
#define _SCTime_H_

#include "J2ObjC_header.h"

@protocol SCTime < NSObject, JavaObject >

- (id<SCTime>)plusDaysWithInt:(jint)days;

- (jint)daysSinceEpoch;

- (jlong)getMillis;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTime)

J2OBJC_TYPE_LITERAL_HEADER(SCTime)

#define UkCoAmlcurranSocialTime SCTime

#endif // _SCTime_H_
