//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeCalculator.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "TimeCalculator.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

@interface SCTimeCalculator : NSObject

@end

__attribute__((unused)) static IOSObjectArray *SCTimeCalculator__Annotations$0();

__attribute__((unused)) static IOSObjectArray *SCTimeCalculator__Annotations$1();

@implementation SCTimeCalculator

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LSCTimestamp;", 0x401, 0, 1, -1, -1, 2, -1 },
    { NULL, "I", 0x401, 3, 4, -1, -1, -1, -1 },
    { NULL, "LSCTimestamp;", 0x401, 5, 6, -1, -1, 7, -1 },
    { NULL, "LSCTimestamp;", 0x401, -1, -1, -1, -1, -1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  methods[0].selector = @selector(plusDaysWithInt:withSCTimestamp:);
  methods[1].selector = @selector(getDaysWithSCTimestamp:);
  methods[2].selector = @selector(plusHoursWithSCTimestamp:withInt:);
  methods[3].selector = @selector(startOfToday);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { "plusDays", "ILSCTimestamp;", (void *)&SCTimeCalculator__Annotations$0, "getDays", "LSCTimestamp;", "plusHours", "LSCTimestamp;I", (void *)&SCTimeCalculator__Annotations$1 };
  static const J2ObjcClassInfo _SCTimeCalculator = { "TimeCalculator", "uk.co.amlcurran.social", ptrTable, methods, NULL, 7, 0x609, 4, 0, -1, -1, -1, -1, -1 };
  return &_SCTimeCalculator;
}

@end

IOSObjectArray *SCTimeCalculator__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SCTimeCalculator__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCTimeCalculator)
