//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeOfDay.java
//

#include "J2ObjC_header.h"

#pragma push_macro("TimeOfDay_INCLUDE_ALL")
#ifdef TimeOfDay_RESTRICT
#define TimeOfDay_INCLUDE_ALL 0
#else
#define TimeOfDay_INCLUDE_ALL 1
#endif
#undef TimeOfDay_RESTRICT

#if !defined (SCTimeOfDay_) && (TimeOfDay_INCLUDE_ALL || defined(SCTimeOfDay_INCLUDE))
#define SCTimeOfDay_

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

@interface SCTimeOfDay : NSObject

#pragma mark Public

+ (SCTimeOfDay * __nonnull)fromHoursWithInt:(jint)hours;

- (jlong)toHours;

- (jlong)toMinutes;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTimeOfDay)

FOUNDATION_EXPORT SCTimeOfDay *SCTimeOfDay_fromHoursWithInt_(jint hours);

J2OBJC_TYPE_LITERAL_HEADER(SCTimeOfDay)

@compatibility_alias UkCoAmlcurranSocialTimeOfDay SCTimeOfDay;

#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#endif

#pragma pop_macro("TimeOfDay_INCLUDE_ALL")
