//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/Time.java
//

#include "J2ObjC_header.h"

#pragma push_macro("Time_INCLUDE_ALL")
#ifdef Time_RESTRICT
#define Time_INCLUDE_ALL 0
#else
#define Time_INCLUDE_ALL 1
#endif
#undef Time_RESTRICT

#if !defined (SCTime_) && (Time_INCLUDE_ALL || defined(SCTime_INCLUDE))
#define SCTime_

@protocol SCTime < NSObject, JavaObject >

- (id<SCTime>)plusDaysWithInt:(jint)days;

- (jint)daysSinceEpoch;

- (jlong)getMillis;

- (id<SCTime>)plusHoursWithInt:(jint)hours;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTime)

J2OBJC_TYPE_LITERAL_HEADER(SCTime)

#define UkCoAmlcurranSocialTime SCTime

#endif

#pragma pop_macro("Time_INCLUDE_ALL")
