//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeOfDay.java
//

#ifndef _TimeOfDay_H_
#define _TimeOfDay_H_

#include "J2ObjC_header.h"

@interface SCTimeOfDay : NSObject

#pragma mark Public

+ (SCTimeOfDay *)fromHoursWithInt:(jint)hours;

- (jlong)toMinutes;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTimeOfDay)

FOUNDATION_EXPORT SCTimeOfDay *SCTimeOfDay_fromHoursWithInt_(jint hours);

J2OBJC_TYPE_LITERAL_HEADER(SCTimeOfDay)

@compatibility_alias UkCoAmlcurranSocialTimeOfDay SCTimeOfDay;

#endif // _TimeOfDay_H_
