//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/Timestamp.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "TimeCalculator.h"
#include "TimeOfDay.h"
#include "Timestamp.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

@interface SCTimestamp () {
 @public
  id<SCTimeCalculator> timeCalculator_;
  jlong millis_;
}

@end

J2OBJC_FIELD_SETTER(SCTimestamp, timeCalculator_, id<SCTimeCalculator>)

__attribute__((unused)) static IOSObjectArray *SCTimestamp__Annotations$0(void);

__attribute__((unused)) static IOSObjectArray *SCTimestamp__Annotations$1(void);

__attribute__((unused)) static IOSObjectArray *SCTimestamp__Annotations$2(void);

@implementation SCTimestamp

- (instancetype)initWithLong:(jlong)millis
        withSCTimeCalculator:(id<SCTimeCalculator>)timeCalculator {
  SCTimestamp_initWithLong_withSCTimeCalculator_(self, millis, timeCalculator);
  return self;
}

- (SCTimestamp *)plusDaysWithInt:(jint)days {
  return [((id<SCTimeCalculator>) nil_chk(timeCalculator_)) plusDaysWithInt:days withSCTimestamp:self];
}

- (jint)daysSinceEpoch {
  return [((id<SCTimeCalculator>) nil_chk(timeCalculator_)) getDaysWithSCTimestamp:self];
}

- (jlong)getMillis {
  return millis_;
}

- (SCTimestamp *)plusHoursWithInt:(jint)hours {
  return [((id<SCTimeCalculator>) nil_chk(timeCalculator_)) plusHoursWithSCTimestamp:self withInt:hours];
}

- (SCTimestamp *)plusHoursOfWithSCTimeOfDay:(SCTimeOfDay *)timeOfDay {
  return [((id<SCTimeCalculator>) nil_chk(timeCalculator_)) plusHoursWithSCTimestamp:self withInt:(jint) [((SCTimeOfDay *) nil_chk(timeOfDay)) hoursInDay]];
}

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, NULL, 0x1, -1, 0, -1, -1, -1, -1 },
    { NULL, "LSCTimestamp;", 0x1, 1, 2, -1, -1, 3, -1 },
    { NULL, "I", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "J", 0x1, -1, -1, -1, -1, -1, -1 },
    { NULL, "LSCTimestamp;", 0x1, 4, 2, -1, -1, 5, -1 },
    { NULL, "LSCTimestamp;", 0x1, 6, 7, -1, -1, 8, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(initWithLong:withSCTimeCalculator:);
  methods[1].selector = @selector(plusDaysWithInt:);
  methods[2].selector = @selector(daysSinceEpoch);
  methods[3].selector = @selector(getMillis);
  methods[4].selector = @selector(plusHoursWithInt:);
  methods[5].selector = @selector(plusHoursOfWithSCTimeOfDay:);
  #pragma clang diagnostic pop
  static const J2ObjcFieldInfo fields[] = {
    { "timeCalculator_", "LSCTimeCalculator;", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
    { "millis_", "J", .constantValue.asLong = 0, 0x12, -1, -1, -1, -1 },
  };
  static const void *ptrTable[] = { "JLSCTimeCalculator;", "plusDays", "I", (void *)&SCTimestamp__Annotations$0, "plusHours", (void *)&SCTimestamp__Annotations$1, "plusHoursOf", "LSCTimeOfDay;", (void *)&SCTimestamp__Annotations$2 };
  static const J2ObjcClassInfo _SCTimestamp = { "Timestamp", "uk.co.amlcurran.social", ptrTable, methods, fields, 7, 0x1, 6, 2, -1, -1, -1, -1, -1 };
  return &_SCTimestamp;
}

@end

void SCTimestamp_initWithLong_withSCTimeCalculator_(SCTimestamp *self, jlong millis, id<SCTimeCalculator> timeCalculator) {
  NSObject_init(self);
  self->millis_ = millis;
  self->timeCalculator_ = timeCalculator;
}

SCTimestamp *new_SCTimestamp_initWithLong_withSCTimeCalculator_(jlong millis, id<SCTimeCalculator> timeCalculator) {
  J2OBJC_NEW_IMPL(SCTimestamp, initWithLong_withSCTimeCalculator_, millis, timeCalculator)
}

SCTimestamp *create_SCTimestamp_initWithLong_withSCTimeCalculator_(jlong millis, id<SCTimeCalculator> timeCalculator) {
  J2OBJC_CREATE_IMPL(SCTimestamp, initWithLong_withSCTimeCalculator_, millis, timeCalculator)
}

IOSObjectArray *SCTimestamp__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SCTimestamp__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SCTimestamp__Annotations$2() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(SCTimestamp)

J2OBJC_NAME_MAPPING(SCTimestamp, "uk.co.amlcurran.social", "SC")
