//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeCalculator.java
//

#ifndef _TimeCalculator_H_
#define _TimeCalculator_H_

#include "J2ObjC_header.h"

@class SCTime;

@protocol SCTimeCalculator < NSObject, JavaObject >

- (SCTime *)plusDaysWithInt:(jint)days
                 withSCTime:(SCTime *)time;

- (jint)getDaysWithSCTime:(SCTime *)time;

- (SCTime *)plusHoursWithSCTime:(SCTime *)time
                        withInt:(jint)hours;

@end

J2OBJC_EMPTY_STATIC_INIT(SCTimeCalculator)

J2OBJC_TYPE_LITERAL_HEADER(SCTimeCalculator)

#define UkCoAmlcurranSocialTimeCalculator SCTimeCalculator

#endif // _TimeCalculator_H_
