//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/TimeRepository.java
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "J2ObjC_source.h"
#include "TimeRepository.h"
#include "java/lang/annotation/Annotation.h"
#include "javax/annotation/Nonnull.h"
#include "javax/annotation/meta/When.h"

@interface SCTimeRepository : NSObject

@end

__attribute__((unused)) static IOSObjectArray *SCTimeRepository__Annotations$0(void);

__attribute__((unused)) static IOSObjectArray *SCTimeRepository__Annotations$1(void);

@implementation SCTimeRepository

+ (const J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { NULL, "LSCTimeOfDay;", 0x401, -1, -1, -1, -1, 0, -1 },
    { NULL, "LSCTimeOfDay;", 0x401, -1, -1, -1, -1, 1, -1 },
  };
  #pragma clang diagnostic push
  #pragma clang diagnostic ignored "-Wobjc-multiple-method-names"
  #pragma clang diagnostic ignored "-Wundeclared-selector"
  methods[0].selector = @selector(borderTimeEnd);
  methods[1].selector = @selector(borderTimeStart);
  #pragma clang diagnostic pop
  static const void *ptrTable[] = { (void *)&SCTimeRepository__Annotations$0, (void *)&SCTimeRepository__Annotations$1 };
  static const J2ObjcClassInfo _SCTimeRepository = { "TimeRepository", "uk.co.amlcurran.social", ptrTable, methods, NULL, 7, 0x609, 2, 0, -1, -1, -1, -1, -1 };
  return &_SCTimeRepository;
}

@end

IOSObjectArray *SCTimeRepository__Annotations$0() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

IOSObjectArray *SCTimeRepository__Annotations$1() {
  return [IOSObjectArray newArrayWithObjects:(id[]){ create_JavaxAnnotationNonnull(JreLoadEnum(JavaxAnnotationMetaWhen, ALWAYS)) } count:1 type:JavaLangAnnotationAnnotation_class_()];
}

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCTimeRepository)

J2OBJC_NAME_MAPPING(SCTimeRepository, "uk.co.amlcurran.social", "SC")
