//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/Time.java
//

#ifndef _UkCoAmlcurranSocialTime_H_
#define _UkCoAmlcurranSocialTime_H_

#include "J2ObjC_header.h"

@protocol UkCoAmlcurranSocialTime < NSObject, JavaObject >

- (id<UkCoAmlcurranSocialTime>)plusDaysWithInt:(jint)days;

- (jint)daysSinceEpoch;

- (jlong)getMillis;

@end

J2OBJC_EMPTY_STATIC_INIT(UkCoAmlcurranSocialTime)

J2OBJC_TYPE_LITERAL_HEADER(UkCoAmlcurranSocialTime)

#endif // _UkCoAmlcurranSocialTime_H_
