//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/Time.java
//


#include "J2ObjC_source.h"
#include "Time.h"

@interface SCTime : NSObject
@end

@implementation SCTime

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "plusDaysWithInt:", "plusDays", "Luk.co.amlcurran.social.Time;", 0x401, NULL, NULL },
    { "daysSinceEpoch", NULL, "I", 0x401, NULL, NULL },
    { "getMillis", NULL, "J", 0x401, NULL, NULL },
  };
  static const J2ObjcClassInfo _SCTime = { 2, "Time", "uk.co.amlcurran.social", NULL, 0x609, 3, methods, 0, NULL, 0, NULL, 0, NULL, NULL, NULL };
  return &_SCTime;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(SCTime)
