//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: core/src/main/java//uk/co/amlcurran/social/CalendarSource.java
//

#ifndef _CalendarSource_H_
#define _CalendarSource_H_

#include "J2ObjC_header.h"

@class UkCoAmlcurranSocialCoreSparseArray;
@protocol SCCalendarItem;
@protocol SCTime;
@protocol SCTimeRepository;

@interface SCCalendarSource : NSObject

#pragma mark Public

- (instancetype)initWithSCTimeRepository:(id<SCTimeRepository>)timeRepository
  withUkCoAmlcurranSocialCoreSparseArray:(UkCoAmlcurranSocialCoreSparseArray *)calendarItems
                                 withInt:(jint)daysSize
                              withSCTime:(id<SCTime>)now;

- (jint)count;

- (jboolean)isEmptyAtWithInt:(jint)position;

- (id<SCCalendarItem>)itemAtWithInt:(jint)position;

@end

J2OBJC_EMPTY_STATIC_INIT(SCCalendarSource)

FOUNDATION_EXPORT void SCCalendarSource_initWithSCTimeRepository_withUkCoAmlcurranSocialCoreSparseArray_withInt_withSCTime_(SCCalendarSource *self, id<SCTimeRepository> timeRepository, UkCoAmlcurranSocialCoreSparseArray *calendarItems, jint daysSize, id<SCTime> now);

FOUNDATION_EXPORT SCCalendarSource *new_SCCalendarSource_initWithSCTimeRepository_withUkCoAmlcurranSocialCoreSparseArray_withInt_withSCTime_(id<SCTimeRepository> timeRepository, UkCoAmlcurranSocialCoreSparseArray *calendarItems, jint daysSize, id<SCTime> now) NS_RETURNS_RETAINED;

J2OBJC_TYPE_LITERAL_HEADER(SCCalendarSource)

@compatibility_alias UkCoAmlcurranSocialCalendarSource SCCalendarSource;

#endif // _CalendarSource_H_
